name: Build Habit Builder APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config \
          zlib1g-dev libncurses5-dev libtinfo5 cmake libffi-dev libssl-dev

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install cython
        pip install buildozer

    - name: Set up Android SDK
      run: |
        # Create Android SDK directory
        mkdir -p ~/android-sdk/cmdline-tools/latest
        cd ~/android-sdk
        
        # Download and extract command line tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip -d cmdline-tools/latest
        rm commandlinetools-linux-9477386_latest.zip
        
        # Set environment variables
        echo "export ANDROID_HOME=~/android-sdk" >> $GITHUB_ENV
        echo "export PATH=$PATH:~/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_ENV
        
        # Accept licenses and install components
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"
        
        # Verify installation
        ls -la ~/android-sdk/build-tools/30.0.3
        echo "export PATH=$PATH:~/android-sdk/platform-tools:~/android-sdk/build-tools/30.0.3" >> $GITHUB_ENV

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: habit-builder-apk
        path: ./bin/*.apk
        retention-days: 30
