name: Build Habit Builder APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Buildozer dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config \
          zlib1g-dev libncurses5-dev libtinfo5 cmake libffi-dev libssl-dev

    - name: Install Buildozer
      run: pip install buildozer

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: habit-builder-apk
        path: ./bin/*.apk
        retention-days: 30
